### ISSUE TITLE
Linux v1-gpl surge-rack 

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge-rack#122]
was able to build Rack v1, BaconPlugs and Fundamental but surge-rack hit a snag

```
mkdir -p build/surge/src/linux
cd surge/src/linux && cc -c ConfigurationXml.S -o ../../../build/surge/src/linux/ConfigurationXml.S.o
g++ -o plugin.so build/src/SurgeVOC.cpp.o build/src/SurgeVCF.cpp.o build/src/SurgeRackGUI.cpp.o build/src/SurgeWaveShaper.cpp.o build/src/SurgeOSC.cpp.o build/src/SurgeWTOSC.cpp.o build/src/SurgeWidgets.cpp.o build/src/Surge.cpp.o build/src/SurgeLFO.cpp.o build/src/UserInteractionsRack.cpp.o build/src/SurgeStyle.cpp.o build/src/SurgeADSR.cpp.o build/src/SurgeFX.cpp.o build/surge/src/common/Parameter.cpp.o build/surge/src/common/Sample.cpp.o build/surge/src/common/SampleLoadRiffWave.cpp.o build/surge/src/common/SurgeError.cpp.o build/surge/src/common/SurgePatch.cpp.o build/surge/src/common/SurgeStorage.cpp.o build/surge/src/common/SurgeStorageLoadWavetable.cpp.o build/surge/src/common/SurgeSynthesizer.cpp.o build/surge/src/common/SurgeSynthesizerIO.cpp.o build/surge/src/common/UserDefaults.cpp.o build/surge/src/common/precompiled.cpp.o build/surge/src/common/dsp/AdsrEnvelope.cpp.o build/surge/src/common/dsp/BiquadFilter.cpp.o build/surge/src/common/dsp/BiquadFilterSSE2.cpp.o build/surge/src/common/dsp/DspUtilities.cpp.o build/surge/src/common/dsp/FMOscillator.cpp.o build/surge/src/common/dsp/FilterCoefficientMaker.cpp.o build/surge/src/common/dsp/LfoModulationSource.cpp.o build/surge/src/common/dsp/Oscillator.cpp.o build/surge/src/common/dsp/QuadFilterChain.cpp.o build/surge/src/common/dsp/QuadFilterUnit.cpp.o build/surge/src/common/dsp/SampleAndHoldOscillator.cpp.o build/surge/src/common/dsp/SurgeSuperOscillator.cpp.o build/surge/src/common/dsp/SurgeVoice.cpp.o build/surge/src/common/dsp/VectorizedSvfFilter.cpp.o build/surge/src/common/dsp/Wavetable.cpp.o build/surge/src/common/dsp/WavetableOscillator.cpp.o build/surge/src/common/dsp/WindowOscillator.cpp.o build/surge/src/common/dsp/effect/ConditionerEffect.cpp.o build/surge/src/common/dsp/effect/DistortionEffect.cpp.o build/surge/src/common/dsp/effect/DualDelayEffect.cpp.o build/surge/src/common/dsp/effect/Effect.cpp.o build/surge/src/common/dsp/effect/FreqshiftEffect.cpp.o build/surge/src/common/dsp/effect/PhaserEffect.cpp.o build/surge/src/common/dsp/effect/Reverb1Effect.cpp.o build/surge/src/common/dsp/effect/Reverb2Effect.cpp.o build/surge/src/common/dsp/effect/RotarySpeakerEffect.cpp.o build/surge/src/common/dsp/effect/VocoderEffect.cpp.o build/surge/src/common/vt_dsp/basic_dsp.cpp.o build/surge/src/common/vt_dsp/halfratefilter.cpp.o build/surge/src/common/vt_dsp/lipol.cpp.o build/surge/src/common/vt_dsp/macspecific.cpp.o build/surge/src/common/thread/CriticalSection.cpp.o build/surge/libs/xml/tinystr.cpp.o build/surge/libs/xml/tinyxml.cpp.o build/surge/libs/xml/tinyxmlerror.cpp.o build/surge/libs/xml/tinyxmlparser.cpp.o build/surge/src/linux/ConfigurationXml.S.o  -lstdc++fs -shared
/usr/bin/ld: plugin.so: No symbol version section for versioned symbol `pthread_mutexattr_init@GLIBC_2.2.5'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
../../compile.mk:52: recipe for target 'plugin.so' failed
make: *** [plugin.so] Error 1

```

**Comment by tank-trax** [comment]
added to line 108 of Makefile

LDFLAGS += -lstdc++fs -pthread

**Comment by baconpaul** [comment]
-pthread or -lpthread? If you could attach the full output of "git diff" I can just apply it as a patch! Thanks.

**Comment by tank-trax** [comment]
Is -lpthread better? I wouldn't know the difference. :smile: I found another resolution for 'pthread_mutexattr_init@GLIBC_2.2.5' that used -pthread so I tried it and it worked.

**Comment by baconpaul** [comment]
I was just asking which you used! Wondered if it was correct without the l or a typo. Will add as stated to ight

**Comment by tank-trax** [comment]
Here you go.

```
git diff
diff --git a/Makefile b/Makefile
index 4dc84cb..f18d760 100644
--- a/Makefile
+++ b/Makefile
@@ -105,7 +105,7 @@ endif
 
 ifdef ARCH_LIN
 SOURCES += surge/src/linux/ConfigurationXml.S
-LDFLAGS += -lstdc++fs
+LDFLAGS += -lstdc++fs -pthread
 
 # This is really a hack but...
 build/surge/src/linux/ConfigurationXml.S.o: surge/src/linux/ConfigurationXml.S

```

**Comment by NielsMayer** [comment]
MeToo:

`                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mkdir -p build/surge/src/linux
cd surge/src/linux && cc -c ConfigurationXml.S -o ../../../build/surge/src/linux/ConfigurationXml.S.o
g++ -o plugin.so build/src/SurgeVOC.cpp.o build/src/SurgeVCF.cpp.o build/src/SurgeRackGUI.cpp.o build/src/SurgeWaveShaper.cpp.o build/src/SurgeOSC.cpp.o build/src/SurgeWTOSC.cpp.o build/src/SurgeWidgets.cpp.o build/src/Surge.cpp.o build/src/UserInteractionsRack.cpp.o build/src/SurgeStyle.cpp.o build/src/SurgeLFO.cpp.o build/src/SurgeADSR.cpp.o build/src/SurgeFX.cpp.o build/surge/src/common/Parameter.cpp.o build/surge/src/common/Sample.cpp.o build/surge/src/common/SampleLoadRiffWave.cpp.o build/surge/src/common/SurgeError.cpp.o build/surge/src/common/SurgePatch.cpp.o build/surge/src/common/SurgeStorage.cpp.o build/surge/src/common/SurgeStorageLoadWavetable.cpp.o build/surge/src/common/SurgeSynthesizer.cpp.o build/surge/src/common/SurgeSynthesizerIO.cpp.o build/surge/src/common/UserDefaults.cpp.o build/surge/src/common/precompiled.cpp.o build/surge/src/common/dsp/AdsrEnvelope.cpp.o build/surge/src/common/dsp/BiquadFilter.cpp.o build/surge/src/common/dsp/BiquadFilterSSE2.cpp.o build/surge/src/common/dsp/DspUtilities.cpp.o build/surge/src/common/dsp/FMOscillator.cpp.o build/surge/src/common/dsp/FilterCoefficientMaker.cpp.o build/surge/src/common/dsp/LfoModulationSource.cpp.o build/surge/src/common/dsp/Oscillator.cpp.o build/surge/src/common/dsp/QuadFilterChain.cpp.o build/surge/src/common/dsp/QuadFilterUnit.cpp.o build/surge/src/common/dsp/SampleAndHoldOscillator.cpp.o build/surge/src/common/dsp/SurgeSuperOscillator.cpp.o build/surge/src/common/dsp/SurgeVoice.cpp.o build/surge/src/common/dsp/VectorizedSvfFilter.cpp.o build/surge/src/common/dsp/Wavetable.cpp.o build/surge/src/common/dsp/WavetableOscillator.cpp.o build/surge/src/common/dsp/WindowOscillator.cpp.o build/surge/src/common/dsp/effect/ConditionerEffect.cpp.o build/surge/src/common/dsp/effect/DistortionEffect.cpp.o build/surge/src/common/dsp/effect/DualDelayEffect.cpp.o build/surge/src/common/dsp/effect/Effect.cpp.o build/surge/src/common/dsp/effect/FreqshiftEffect.cpp.o build/surge/src/common/dsp/effect/PhaserEffect.cpp.o build/surge/src/common/dsp/effect/Reverb1Effect.cpp.o build/surge/src/common/dsp/effect/Reverb2Effect.cpp.o build/surge/src/common/dsp/effect/RotarySpeakerEffect.cpp.o build/surge/src/common/dsp/effect/VocoderEffect.cpp.o build/surge/src/common/vt_dsp/basic_dsp.cpp.o build/surge/src/common/vt_dsp/halfratefilter.cpp.o build/surge/src/common/vt_dsp/lipol.cpp.o build/surge/src/common/vt_dsp/macspecific.cpp.o build/surge/src/common/thread/CriticalSection.cpp.o build/surge/libs/xml/tinystr.cpp.o build/surge/libs/xml/tinyxml.cpp.o build/surge/libs/xml/tinyxmlerror.cpp.o build/surge/libs/xml/tinyxmlparser.cpp.o build/surge/src/linux/ConfigurationXml.S.o  -lstdc++fs -shared
/usr/bin/ld: plugin.so: No symbol version section for versioned symbol `pthread_mutexattr_init@GLIBC_2.2.5'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
../../compile.mk:52: recipe for target 'plugin.so' failed
make: *** [plugin.so] Error 1
`

It is fixed by applying aforementioned change to Makefile.

**Comment by baconpaul** [comment]
Yeah I’ll apply it tonight - thanks!

**Comment by baconpaul** [comment]
OK you should get it if you pull master
