### ISSUE TITLE
Example patch crashes Rack

### ISSUE THREAD

**Issue by SteveRussell33** [surge-synthesizer/surge-rack#203]
The patch RotaryExample.vcv doesn't load and crashed Rack v1.dev build

From log.txt
[10.355 info src/SurgeModuleCommon.hpp:87] [SurgeRack] Instance: Module=ADSR BuildInfo=os:win pluggit:e8bb3a4 surgegit:df47e07 buildtime=Jun  9 2019 18:41:18
[10.558 warn src/UserInteractionsRack.cpp:14] Surge Error
Surge is not properly installed.
Cannot find 'configuration.xml' in path './plugins/SurgeRack/surge-data/'. Please reinstall surge.

[10.558 warn src/UserInteractionsRack.cpp:14] Surge Error
Surge Installation Error
Surge was unable to load wavetables from './plugins/SurgeRack/surge-data/'. The directory contains no wavetables. Please reinstall using the Surge installer.

[10.574 info src/SurgeModuleCommon.cpp:87] [SurgeRack] SurgeStorage::dataPath = ./plugins/SurgeRack/surge-data/

The problem is (from makefile)
build/surge-data:
	mkdir -p build/surge-data
	cp surge/resources/data/configuration.xml build/surge-data
	cp surge/resources/data/windows.wt build/surge-data
	cp -R surge/resources/data/wavetables build/surge-data/wavetables
	cp -R surge/resources/data/wavetables_3rdparty build/surge-data/wavetables_3rdparty

DISTRIBUTABLES += $(wildcard LICENSE*) res docs patches README.md build/surge-data

The dist package places the surge-data folder under a folder called build yet - as you can see above - the SurgeRack plugin expects the surge-data folder to be under the SurgeRack folder in ./plugins
Manually moving the surge-data folder to ./plugins/SurgeRack/ and deleting the build folder the patch loads correctly.

**Comment by baconpaul** [comment]
Ahh right. So here is why this works for me (and will work in community but I agree doesn't work for you).

The distributable all get added to the zip file with their lowest directory. So the zip file contains a directory called "surge-data" which when you unzip it at install gives you the path you see.

Of course, when you are building the zip file you don't want that splatting your git directory so I put it in build.

But then if you make all as a subdirectories of rack and don't install the zip you get the error you see.

So what to do. I don't really want to put surge-data in the top of the source directory. It is transient copies form the sub-module. When you make and install a zip it all works fine. (That's how I have set up my workflow).

Perhaps the thing to do is

1. Add a .gitignore for ./surge-data
2. In the rule that makes surge-data make a soft link from build/
3. Add it to the clean

Or just "don't put it in build and still add the gitignore"

What I don't want is to see all those things in my git status and to have them not be cleaned when I clean which is why I went the route I did.

wdyt?

**Comment by baconpaul** [comment]
Another solution is when we initialize SurgeStorage to check if surge-data exists, and if it doesn't, check if build/surge-data exists, and then use the right path to initialize the storage.  So that would be a fs::is_directory in SurgeModuleCommon.cpp right where dataPath is assigned. I think that's probably the cleanest solution. 

Happy for you to do that also. The project is open for PRs! Like I said, I don't build as a sub-dir of rack, I build away from the rack tree and install the .zip files and .so into the user dir so this hasn't broken me but should def be fixed!

**Comment by baconpaul** [comment]
Actually no hold on I think I am wrong... looking.

**Comment by baconpaul** [comment]
Yup I am wrong and had a stale directory making it work for me. 

Hold on - I will get this cleaned up right now and do a push.

**Comment by baconpaul** [comment]
OK so here's a cleaner diagnosis.

this diff in Rack

```
paul:~/dev/VCVRack/V1.0/Source/Rack$ git diff 95ea82c2aba6b2a7e37a9e59bf6edde59e824108 114cc58f05de8cf9e5b689d0bbf63780be4278a9 plugin.mk 
diff --git a/plugin.mk b/plugin.mk
index 574c90c..906d98f 100644
--- a/plugin.mk
+++ b/plugin.mk
@@ -62,11 +62,7 @@ else
        $(STRIP) -s dist/$(SLUG)/$(TARGET)
 endif
        @# Copy distributables
-ifdef ARCH_MAC
-       rsync -rR $(DISTRIBUTABLES) dist/$(SLUG)/
-else
-       cp -R --parents $(DISTRIBUTABLES) dist/$(SLUG)/
-endif
+       cp -R $(DISTRIBUTABLES) dist/$(SLUG)/
        @# Create ZIP package
        cd dist && zip -q -9 -r $(SLUG)-$(VERSION)-$(ARCH).zip $(SLUG)
```

changes the behavior of "build/surge-data" in dist. But I had an old version of surge-data so I didn't see the change. When I clean out my user area I see what you do.

I have a change coming now to include the build/ name in the search which will fix this.

Thank you. Only a clean builder would have seen this!

**Comment by baconpaul** [comment]
OK fix is in. If you do a git pull you should be good to go. Thanks!

**Comment by SteveRussell33** [comment]
No problem, looks good; glad to help!

**Comment by baconpaul** [comment]
Yup thanks. Please let me know what else you find! As far as I know it’s mostly folks pretty deep inside the project who have been playing with these so far and so a fresh view on them could really be useful!

**Comment by SteveRussell33** [comment]
I tried your latest Nightly alpha build 1.alpha.e4c0384. Patch crashes.
The package has /surge-data in the "root" SurgeRack folder.

My suggestion would be to undo commit f4ef39de89643b48484cf58d5bc89b30c04e9136 and all should be good as you have it now in terms of packaging.

HTH

**Comment by baconpaul** [comment]
I just did a clean build of surge-rack against Rack 97e892f8658296993c3bc729fc16a140b616a1f3 and if I look in dist, I get surge-rack in the build directory.

Which platform and which Rack version are you building against? I wonder if you are on one that has the old behavior. Or if the behavior is different mac to win.

Thank you

**Comment by SteveRussell33** [comment]
I'm on Win 10 Rack 12524373445bcc6698a9d8562cd5553600d7292f (June 6th) which should be OK as there's no commits that I can see that would influence this.

Did a make clean and make dist on latest surge-rack e4c0384e4724b8fad7fc4b1360a85d23eea1a2de today and it has surge-data in the SurgeRack/build dir as per surge-rack commit f4ef39de89643b48484cf58d5bc89b30c04e9136.
As in my previous comment your alpha build dist from "release" tab doesn't follow this behavior.
Personally I think the surge-data dir should be under SurgeRack (alpha build behavior) and not build/surge-data; I think it's "neater" this way. Let me know your thoughts.

Glad to be of help

**Comment by baconpaul** [comment]
Ahh damnit yes of course. The nightlies build from the last sdk release which doesn’t have the diff I pasted above. So the sdk will make surge-data and the head of source will make build/surge-data. 

Guess I will write the either or code when I get home and leave it there until 1.0 is final!

**Comment by baconpaul** [comment]
Ahh damnit yes of course. The nightlies build from the last sdk release which doesn’t have the diff I pasted above. So the sdk will make surge-data and the head of source will make build/surge-data. 

Guess I will write the either or code when I get home and leave it there until 1.0 is final!

**Comment by baconpaul** [comment]
OK I'm pushing an either-or solution for now so people can build with various vintages of V1.0 source and SDK. Once V1.0 stabilizes I will remove the either-or above.
