### ISSUE TITLE
BiQuad Filter Craps Out/Blows Up beta1.2

### ISSUE THREAD

**Issue by Petervos2018** [surge-synthesizer/surge-rack#275]
The BP BP2A and PKA modes all crap out when the freq it set above 20000 Hz (It goes to 25088 ?)
Easy to test, connect something, open the freq and Poof the sound blows up past 20000 Hz and won't come back until you replace the filter.
Love the colour scheme !

Greetings Peter

**Comment by baconpaul** [comment]
Oh thanks. The answer is almost definitely going to be "set the max frequency lower in the UI" - sorry about that bad range.

I added a nan check in this release since it used to not only crap out it also spouted nans (that was #250) but should have tested the full range on all flavors.

I'm getting a surge 1.6.4 release ready which will have me update these modules then too. Appreciate the report.

Glad you like the colors!

**Comment by baconpaul** [comment]
OK have a fix in place both for the knob and for CV driving the frequency out of range too. I use the semantic on GitHub that I close issues when the fix is in master, so that will close this issue and then our nightly release will include it. Will take a while more before we get the release in the plugin manager. If you'd like to test it we have all platform builds at the releases page about 20 minutes after a push.

**Comment by Petervos2018** [comment]
Thank you !
Peter.
