### ISSUE TITLE
WaveTable compatibility

### ISSUE THREAD

**Issue by docb** [surge-synthesizer/surge-rack#544]
- When i load a wavetable as .wav produced with WaveEdit it loads and displays but the output stays zero.
- I cannot load .WAV only .wav
- Feature: if loading wav is supported then a switch between table sizes like in VCV WTVCO would be nice as in a wav file there may be no info about that (wavecount or wavesize)

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Overview-Of-Wavetables-In-Surge

WaveEdit I bet is loading as a one-shot since it has no tags or loop markers. We don't (currently) have a 'rebuild with frames and count' feature in surge and instead rely on tags in the actual file, loading files from a variety of properties and following their tagging. WavEdit doesn't tag (and moreover uses libsndfile which doesn't let you add extra RIFF/WAV chunks to tag) so you have to tag post-fact right now. 

The .WAV not .wav is a bug though and I'll fix that before release for sure! Thanks!

**Comment by docb** [comment]
ok, here i found a description how to convert
https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Creating-Wavetables-With-WaveEdit
It works like so:
- Download e.g. https://waveeditonline.com/wav/ENSONIQ_.WAV
- `cd surge-rack-xt/surge/scripts/wt-tool`
- `python3 normalize-i16-to-i15.py -n half ~/Downloads/ENSONIQ_.WAV ~/Downloads/ENSONIQ_1.wav`
- `python3 add-surge-metadata.py -i -s 256 ~/Downloads/ENSONIQ_1.wav`
then ENSONIQ_1.wav  can be loaded and it works.

**Comment by baconpaul** [comment]
OK great yes that's what you have to do today. We want to address this in surge proper in a more fulsome fashion and when we do we will lift that code into rack of course.

I'm going to close this and make the wav/WAV a separate small issue.

Thanks!

**Comment by baconpaul** [comment]
@docb what Os do you run please? It will matter a bit for the .WAV thing

**Comment by docb** [comment]
@baconpaul 
>what Os do you run please?
Linux
