### ISSUE TITLE
LFO x EG output stops on adjusting envelope (linux)

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#557]
When adjusting the envelope sliders, sooner or later the output stops, once this happens, setting delay & attack back to zero restores it.
This is possibly a fundamental misunderstanding on my part?

![image](https://user-images.githubusercontent.com/12547379/200039694-fad303e8-7447-4f7d-98bc-ceac679b2ea3.png)

**Comment by ContemporaryInsanity** [comment]
I also note that I see brief output when I connect or disconnect to TRIG or TRIG ENV even if the cable is at constant zero volts.

**Comment by ContemporaryInsanity** [comment]
Also, a moving cursor like on ShapeMaster would be visually informative.

**Comment by baconpaul** [comment]
So the envelope is a DAHDSR envelope. The trigger is keeping it open. So if you have a long enough delay you jump from delay -> release right away unless the release is set at "forever" which is a special case.

A good way to understand this is to plumb both the LFOxEG and the EG output into a scope so you can see the enclosing envelope.

The brief blip when you disconnect is because disconnecting triggers a fresh envelope, and that's just like attaching a trigger to it. Again in the release infinite case or when just outputting the LFO portion, this is useful.

A visual indicator is a good idea. pyer suggested one on the step sequencer also. Let me think about how we might do that (since the sustain phase is of indeterminate time obviously). I'll open a separate issue for that.

**Comment by baconpaul** [comment]
Great and #558 is the "draw a dot" issue.

**Comment by ContemporaryInsanity** [comment]
Got my head around most of it now I think, however, what's the difference between TRIG & TRIGENV?

**Comment by ContemporaryInsanity** [comment]
Also, click to set step on step sequencer would be faster than click & vertical drag.
Bonus points for click & horizontal drag to draw shapes.

**Comment by baconpaul** [comment]
TRIG retrigs the entire LFO; so starts the envelope *and* the underlying waveform from initial phase
TRIGENV retrigs the env but not the waveform so you don't get a phase jump
There is an open issue (#541) that the envelope does not preserve value when retriggered from non-zero which is on my weekend hitlist

**Comment by baconpaul** [comment]
> Also, click to set step on step sequencer would be faster than click & vertical drag.
> Bonus points for click & horizontal drag to draw shapes, see voxglitch sequencers.

Yeah surge proper has all these features and more (including things like quantized drags to 1/12 and draw an arrow for a line). Porting them is hard - especially since I did each as a slider - but let me open a separate issue for this and put it mostly post 1.0.
