### ISSUE TITLE
Wavetable VCO navigation in display doesn't match menu

### ISSUE THREAD

**Issue by paulpiko** [surge-synthesizer/surge-rack#585]
Using SurgeXTRack-2.0.beta.0-nightly-dd6ebb9-win.vcvplugin, Windows10

For example, when on Emu / Voices And Animals / Yoobee, pressing the right arrow in the top right of the display area loads Layzer / Morphs / Morph 1. According to the wavetable menu the next wave should have been Emu VSCO / Brass / STAC French Horn.

Using the nav arrows, Emu VSCO / Brass / STAC French Horn comes immediately after Damon Armani / Damon Armani 28. 

After the last of the Emu VSCO, the first of the Emu wavetables is loaded. In the menu Emu precedes Emu VSCO.

**Comment by Andreya-Autumn** [comment]
Confirmed. Good news is nothing else is out of order, it's just the menu is Emu -> Emu VSCO, but the nav buttons are Emu VSCO -> Emu.

**Comment by baconpaul** [comment]
Thank you!

**Comment by baconpaul** [comment]
I wonder if surge proper has the same bug now I think of it.

**Comment by Andreya-Autumn** [comment]
Sure does! :)

**Comment by baconpaul** [comment]
Excellent!

**Comment by baconpaul** [comment]
Sigh. If you compare we were lazily sorting full paths, And "EMU" < "EMU VSCO" but "EMU VSCO/Foo" < "EMU/Bar"

So the list sorted "EMU" "EMU VSCO" "EMU VSCO/FOO", "EMU/BAR"

which is why you got the wrong ends attached

I fixed it upstream in surge with a path-aware sort. WIll try and get it merged rack side tonight also.

Sharp eyes. This bug has been in surge for about 2 years. Thanks!
