### ISSUE TITLE
New Module - Quad AD Envelope Generator

### ISSUE THREAD

**Issue by Torinbob** [surge-synthesizer/surge-rack#633]
## BaconPaul Edit Todos

- [x] Do we want non percentage mod typein values?
- [x] Feedback from Steve:
     - [x] We really need some padding around the AD envelope shapes so there is some space between them and the grey divider lines (like there is on Quad LFO). 
     - [x] A little padding around the small 'A' and 'D' curve shape selectors would help too - ideally they shouldn't come so close to touching the grey lines at the top and sides.
     - [x] On the arrows between the trig buttons, ideally we want them to look like they are all centred between the jacks (whether circle, right arrow or left arrow). Currently I would say the right arrow should move a little to the right and the left arrow should move a little to the left. This may be a visual thing due to the shape - the 'pointy' end will look further away from the jack than the 'thick' end, even if the space is exactly the same. Also it looks like the 'thick' end of the arrows are missing their black outline, which would actually make the visual centering issue more problematic if it was visible - see my screengrab where I have kept the mouse pointer over the centre of the original circle in each example.

## Original Message

Does what it says on the tin :)

Would be good to have control over the Attack and release curves.

Initial idea:

<img width="450" alt="Quad AD" src="https://user-images.githubusercontent.com/41232273/201737657-d3ff3273-b148-4d08-a93b-27ed76ede0e3.png">

**Comment by baconpaul** [comment]
Great 

I put this in 1.1 because I think “4x a foobar” will become a bit of a pattern so want to remember to code the 4x s that way

**Comment by Torinbob** [comment]
Great thanks - Looks like 1.1 is gonna be "Revenge of the modulators!"

**Comment by baconpaul** [comment]
ha ha! plus better labels. but the stereo mod on ws and filter i'm really excited about.

**Comment by Andreya-Autumn** [comment]
> but the stereo mod on ws and filter i'm really excited about.

Same! :)

**Comment by baconpaul** [comment]
Convo with Pope Kehoe

Pope Kehoe III (he/him) — Today at 8:58 PM
I am very excited for the quad AD
the modulation system used in surge xt modules gives a real concrete reason for a quad module instead of just a single AD module you use four times
shame it doesn't have the vertical space to spare some EoC trigger outputs for chaining them, but that's the kinda feature creep that quickly ends with it becoming a full clone of makenoise maths
baconpaul — Today at 9:45 PM
oh i could add a 'chain' mode i suppose in the RMB. "Chain 1->2 if untriggered" and so on
that's pretty easy
heck even put it in the display area as a little arrow between the displays
that's a good idea
