### ISSUE TITLE
Add a DC Blocker Option to the waveshaper (all models)

### ISSUE THREAD

**Issue by MaZe6K** [surge-synthesizer/surge-rack#658]
The Waveshaper can produc e massive DC offsets, too. It might be nice if a DC filter was available here, too.

**Comment by baconpaul** [comment]
So the ones which map zero to non-zero have a filter built in already

The others which are not equal power do not. But nothing stopping me making one you can toggle on in a future release sure! I have the code sitting around. I'll tag it into the 2.1 milestone.

**Comment by baconpaul** [comment]
So the real problem here is the bias control which can make massive DC offsets obviously

Anyway I've added a filter and for now have made it on by default; my tests seem to show this doesn't impact spectra in sine wave tests so I'm happy with it but depending on how 2.1 beta testing goes we may make the default off by default.

In order to not break 2.0 patches though, if you stream from 2.0 it will stay off. Should be in the beta today.
