### ISSUE TITLE
Surge XT 2.0.3.0 in VCV Rack Library broken on macOS

### ISSUE THREAD

**Issue by jaffasplaffa** [surge-synthesizer/surge-rack#675]
Hey :) 

I've been trying to make these work on Mac, but with no luck.

1. Install from VCV lib.
2. Open VCV2 and update and close and open VCV2.
3. Plugins seems to be installed in plugin folder, but they do not show up in VCV2.
4. Update tab shows red dot again, asking me to update Surge, which I do. 
5. Go back to step 2 and repeat.

I can do this close/open update loop forever, nothing happens, the plugins doesn't show up inside VCV2.

I am on an M1 Macbook, using VCV2 Pro 2.2.0

**Comment by baconpaul** [comment]
Yes
the mac library version isn't working. We have a fix (which requires a change to the mac rack toolchain) since the compiler the library uses to build plugins was missing a component.

If you want to use surge today you can get the binary vcvplugin here: https://github.com/surge-synthesizer/surge-rack/releases/tag/v2.0.3.0

Alternately you can wait until we fix the library version. With the rack team we fixed the toolchain problem yesterday so it should be soon enough.

Sorry for this inconvenience.

**Comment by baconpaul** [comment]
Oh and I'll leave this open but will close it once the library is updated

**Comment by baconpaul** [comment]
Oh I also pinned this issue in case others come along looking for the same

**Comment by jaffasplaffa** [comment]
Thanks, I installed the version you posted here and it works :)

**Comment by baconpaul** [comment]
The library version also was fixed this afternoon so closing and unpinning this. Thanks!
