### ISSUE TITLE
v2.0.x bugfix branch

### ISSUE THREAD

**Issue by falkTX** [surge-synthesizer/surge-rack#695]
For being able to have surge with latest fixes but without alpha/testing modules, would be great to have a dedicated bugfix branch.

I am using https://github.com/CardinalModules/surge-rack/commits/v2.0.3.0-cardinal right now for Cardinal.
Builds and tests running https://github.com/DISTRHO/Cardinal/actions/runs/3614341999

**Comment by baconpaul** [comment]
Great if that works for you o will cherry pick those onto a next branch with an appropriate name and tag that won’t screw up our ci and stuff 

again appreciate you upstreaming stuff. Makes maintenance so much easier

**Comment by falkTX** [comment]
I am going to try again an LTO build, but this time giving it some debug symbols so hopefully I am able to find out why that one is crashing.
Afterwards should be safe to have the hotfix/bugfix branch, and I will merge the surgext to main Cardinal branch too.

**Comment by baconpaul** [comment]
Ok I’ll wait to hear 

wonder what the lto thing is - I’ve never used it so I’m no help alas but there is some static initialization we depend on in a few spots in the parameter model mapping to the parent ui which runs even engine only which is all in skinmodel in src/common?

**Comment by falkTX** [comment]
so this was an issue in surge, fixed by https://github.com/surge-synthesizer/surge/pull/6728

**Comment by falkTX** [comment]
sorry I commented on the wrong ticket!

**Comment by baconpaul** [comment]
no worries. there were a lot this weekend.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge-rack/tree/release-candidate/2.0.4.0

[6c5575a](https://github.com/surge-synthesizer/surge-rack/commit/6c5575a026a3f38443f2b6204314a6da46a05ad3)

that contains all the fixes we figured out this weekend plus one small bug fix against 2.0.3.0, cleans out the 2.1 code which got ridden along, makes the version 2.0.3.1

I don't know if we will do a 2.0.4.0 but if we do it will start from the branch plus whatever else we sweep.

Closing this since I think we're done now.
