### ISSUE TITLE
Wave and Windows VCOs - duplicated menu

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#814]
Hi,
Cosmetic issue in V2.1.0.0. I accidentally clicked "Download Extra Wavetable Content" twice. Now I have duplicated context menu entries for the wavetables.

Restarting Rack did not fix it.

![image](https://user-images.githubusercontent.com/14888092/214751506-92b73ad8-9db7-4789-96c5-7d3239ccae56.png)

**Comment by baconpaul** [comment]
Did you have 2.0.3.0 installed?

I bet you have the content twice. Can you see if `Documents/Rack2/plugins/SurgeXTRack/build/surge-data` contains `wavetables_thirdparty`? If it does and you remove that directory, does the duplication end

the problem is rack doesn't remove old content on upgrade. I think you have the content lingering from 203 and downloaded afresh from 21 so the duplication is "legit"

if this *is* the problem the i'll think about how to detect it so this doesn't happen but lets check that first

**Comment by therealkitman** [comment]
I did have 2.0.3.0 installed then upgraded to 2.1.0.0.

Yes, removing that `.Rack2/plugins/SurgeXTRack/build/surge-data/wavetables_thirdparty` (I'm on linux) folder removed the dups after restarting.
