### ISSUE TITLE
EGxVGA (maybe) bug with ADSR settings

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#816]
The A,D and R sliders on the plugin have a minimum value of 0.0039s instead of 0.  I'm assuming this is why the EG curve is trapazoid and not rectangular when those settings are at minimum?

![image](https://user-images.githubusercontent.com/14888092/214781521-54e11b37-7910-4071-b926-6734caaa6146.png)

**Comment by baconpaul** [comment]
so this is kinda-a-bug 

0.0039 = 2^-8 seconds basically; we use a 2^int scaling on that slider.

The problem is when we render the waveform in the panel. We make the envelope gate time == 4/3 (A+D+R) so we can see the sustain. This lets you see the envelope shape. But in this all-min case means the display is showing you the result of, like, a 0.07 second gate or something silly like that.  If you use a real gate and stick the env output into a scope you will see a rectangle at the control timescale

I'll fix this so there's a minimum gate time no matter ADR.

I can also change 0.0039s string display to be "minimum" or something like that in the formatter perhaps.

Will look at both.

**Comment by therealkitman** [comment]
YOu're right, the ENV is shaped as expected. Leave it with you :)

![image](https://user-images.githubusercontent.com/14888092/214981062-eefae765-6410-4f52-8ba5-569ec03691e1.png)

**Comment by baconpaul** [comment]
Ahh for a separate reason I'm going to need to make a little 2.1.1 update so I will sweep fixes into these also when I go

You will see the issues close when I merge the fix. That means the nightly here will be ready 30 minutes after. Library "soon enough"

Thanks
