### ISSUE TITLE
LFOxEG - GATE vs GATEENV What's the Difference?

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#850]
Hi again,
doing more fiddling with LFOxEG. What is the difference between the GATE and GATEENV triggers? If I use one or the other I get the same wave shapes out off LFO, EG and LFOxEG outputs.

![image](https://user-images.githubusercontent.com/14888092/220271145-8122f8bc-d3be-4d49-ba52-90eebeb2893a.png)

![image](https://user-images.githubusercontent.com/14888092/220271269-90a4bcbf-4261-4f95-8067-8adeb0b2c8b0.png)

**Comment by Andreya-Autumn** [comment]
The idea is to provide separate control of the LFO and the EG part, but doing a quick check now, something seems off indeed. We will investigate. Thanks for the report!

**Comment by baconpaul** [comment]
Gate will re attack the entire lfo including the waveform phase set to zero. Gateenv will only reset the envelope so you don’t get a waveform discontinuity. At least that’s the intent

**Comment by Andreya-Autumn** [comment]
Ah, of course. And it is in fact doing that. The manual is unclear on this point, I can fix that soonish.

**Comment by baconpaul** [comment]
Thanks!

I created a 2.1.4 milestone also for some of these smaller things and hopefully can get em in Feb

**Comment by Andreya-Autumn** [comment]
@therealkitman I just updated the manual to clarify what the current behavior does. It was very vague previously, if not misleading. Thanks for the heads up! :)

Also, after discussing it a bit, we're considering some improvements to this behavior. Specifically, if user patches both gate ins (not currently recommended), Gate could change to Reset. That input would then reset LFO phase on trig, and gateenv alone control EG. We can also ponder if the current naming could be made clearer somehow. 

So leaving this issue open for now.

**Comment by therealkitman** [comment]
Thanks. Will re-read the manual tonight.

**Comment by baconpaul** [comment]
ahh so this is really quite a pain;

the problem is the surge LFO has a 'restart the envelope' and a 'restart the envelope and wave' but no 'restart just the wave' option right now. writing that is kind of difficult too.

I'm going to bump changing anything other than the manual here out of 2.1.4. What we really want is when you plumb gateenv that the gate changes to wavetrig as a label and a function; but we don't have that function and it's not a point release refactor to get it alas.

**Comment by Andreya-Autumn** [comment]
Right! Unfortunate but no biggie. The manual changes are taken care of already for the present scenario, so that's all good for now then.

**Comment by baconpaul** [comment]
OK so right now if

1. GateENV is hooked up and triggered the env restarts and the wave does not
2. GATE is hooked up and triggered the env and wave both restart
3. Both hooked up requires *both* gated for anything to happen

I propose we change 3 so that both hooked up means *either* gated is a gate but env going 0->1 restarts env and gate going 0->1 restarts wave but not env

**Comment by baconpaul** [comment]
<img width="1049" alt="Screen Shot 2023-07-04 at 6 42 17 PM" src="https://github.com/surge-synthesizer/surge-rack/assets/13387561/abde9506-be4a-4623-8459-e72ebf512bcf">

Useful test patch here.

**Comment by baconpaul** [comment]
ugh this one is sooooo confusing in the dual case

I'm gonna need to draw the little state machine from the code. May not make 2.2. Certainly wont' make "todays 2.2 wrap up session" though.

**Comment by Andreya-Autumn** [comment]
If it doesn't make it in don't worry about it. 

So, I think we basically agree a much better choice would've been naming them "Gate" and "Reset" and make the reset not gate anything. It's easy to patch the same gate to both if you want them to always reset when re-gating. Any other scenario I can think of is also solveable with a little gate-to-trig module on the side. Right?

...That's indeed a breaking change. We could maybe move this to a later milestone to get some more time and, ask the community how they'd feel about it? I know we obviously can't reach everyone who may be affected etc... But maybe this one is worth taking a risk on because of how confusing it is? What do you think?

**Comment by baconpaul** [comment]
Yeah the reason it’s hard is because the code is a silly mess. I want to fix that anyhow

**Comment by Andreya-Autumn** [comment]
Well, godspeed! :)

**Comment by baconpaul** [comment]
Couple of hours break and I was able to sort it out. PR in!
