### ISSUE TITLE
VCF - UI Request

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#855]
Since you like my sending you issues here's a UI request :laughing: 
Can the VCF have a context menu to select which polyphony channel is being displayed on the graph and modulated controls?

In my mock up video I have both the Frequency and Drive knobs modulated by MOD1 which has in this example 2 polyphony channels. Manually modulating channel 1 is evident on the plugin as the graph area and knobs indicate the modulation. But if I modulate channel 2 nothing is obvious even though the output as seen in the analyzer is.

For your consideration.

PS. A waveform of the oscillators as a shadow trace in the graph area would be even cooler. :+1: 
https://user-images.githubusercontent.com/14888092/220546603-6a0bff7a-4fb5-4c36-8dc2-4d0fb1322104.mp4

**Comment by Andreya-Autumn** [comment]
Oh, I see this one didn't get labeled or responded to. Sorry! Anyway, these are both very good QOL proposals. 
I don't know if it'll make the next point release, so will assign it to a later milestone for now. Thanks for another thoughtful request.

**Comment by baconpaul** [comment]
OK so I've been playing with this some as we approach 2.2

https://www.youtube.com/watch?v=lX0nZm5NlsQ

here's the VCO set up so that the other poly channels behind channel 0 show as ghost lines. This would obviously be an option.  but before I do the rigamarole of applying that to WS and VCF and adding an option and so on: is it useful?

I would probably need to have it off by default at least on the VCF. The CPU usage is not low.

Thoughts welcome.

**Comment by baconpaul** [comment]
That's `baconpaul/ghost-lines-855` just so i remember how i did it.

**Comment by baconpaul** [comment]
So the ghost lines don't help and just make blurs in most cases

Menuy to select display poly inbound shortly for VCF, WS and VCO.
