### ISSUE TITLE
Animated Sliders for EGxLFO and VCAxEG

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#868]
HI. This is a feature request.
Can the sliders on the 2 EG related modules have visual feedback that they are being modulated like the knobs have?
Thanks.

https://user-images.githubusercontent.com/14888092/223013854-a7def95a-f8bc-4f85-8ec5-6e5b30a03c21.mp4

**Comment by Andreya-Autumn** [comment]
Good idea too!

**Comment by baconpaul** [comment]
![OnSlider](https://github.com/surge-synthesizer/surge-rack/assets/13387561/a7ed0a0c-9d36-451d-ae8f-76298e2138c5)

There we go. Should be in next nightly. Works on all sliders. (Ignore the big "DBG" in the corner there - that's just a marker you get if you do a debug rather than release build locally).

**Comment by therealkitman** [comment]
I have to say that I'm impressed :+1:  :1st_place_medal: 

Thank you!!!
