### ISSUE TITLE
Reverb 1 - No sound with modulated Size knob.

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#871]
This may just be my inexperience with Reverbs in general, but -

I was comparing Reverb1, Reverb2 and Plateau just for fun and my learning curve. I saw that if I modulated the Size controls on Reverb 2 and Plateau I still get similar (but weird) audio. But if I modulate Size on Reverb1 the audio cuts out altogether. Even when I manually move Reverb1's Size the audio cuts out. Should it? Are there some controls that should never be modulated and thus be disabled from being so?

https://user-images.githubusercontent.com/14888092/223357111-d80c5879-99b2-4dcb-8697-0d7f2f203f36.mp4

**Comment by baconpaul** [comment]
That sounds like a bug not an intended behavior yeah - will look

**Comment by baconpaul** [comment]
OK I looked into this.

The problem is <https://github.com/surge-synthesizer/sst-effects/blob/0f29ca4c2fb82cf1704ea6dfbdc50b6838d2f849/include/sst/effects/Reverb1.h#L317> that changing the room size clears the buffers. 

I need to think about what to do with this. *probably* fix the reverb1 effect is the thing to do, but there's some nasty branches in surge being ahead of rack which make this a bit tricky. So for now I'm going to mark this as 'expected but tricky to fix' and push it into a 2.2 milestone.
