### ISSUE TITLE
Feature request: Linear time control for Delay module

### ISSUE THREAD

**Issue by rafaelferreiraql** [surge-synthesizer/surge-rack#995]
You know how the Time knobs on Delay affects time in an exponential scale, or something similar? I'd wish to have an option to set that scale to linear instead (mostly for predictable CV modulation purposes), perhaps on the right click menu.
Thanks!

**Comment by Andreya-Autumn** [comment]
Hello, and thanks for the interest! 

Presently, a modulation input of plus one volt doubles the delay time and minus one volt halves it. That seems predictable to me, but perhaps it isn't always! I'm curious to understand what your use case is exactly?

**Comment by rafaelferreiraql** [comment]
> Hello, and thanks for the interest!
> 
> Presently, a modulation input of plus one volt doubles the delay time and minus one volt halves it. That seems predictable to me, but perhaps it isn't always! I'm curious to understand what your use case is exactly?

Yes, my use case would be using 100% wet, no-feedback delay as a time manipulation effect, controllable by CV. It's harder to accurately modulate time that way on an exponential scale (think for example doing stutter effects a la Gross Beat)

**Comment by Andreya-Autumn** [comment]
Ahh, right. That makes total sense.

I also really enjoy such delay/buffer glitch effects (TIME-1 is a great one if you happen to be using Reaper, as an aside). We have a request for such a module logged at #632, and in my opinion the idea would be better suited as a separate module rather than a mode of the Delay. 

As for actually implementing it, the team is trying to focus on other projects right now. So I don't wanna promise that we'll make such a module soon (unless more volunteer devs show up who wanna do it!), but it is a good request and something we're interested in doing at some point! 

In the meantime, I can warmly recommend Prince of Perception (or Prism of Perception if you're willing to spend money) by Flag for this purpose. It's not solely focused on this purpose, but is certainly more suited to it than the Surge delay. 

I'll close this issue as duplicate if you don't mind, feel free to comment further on issue 632 if you have something to add. Cheers!

**Comment by rafaelferreiraql** [comment]
I do suspect it'd be more simple and painless to just add linear correlation as an option, though i'm not really a module coder so I may be wrong about it.
It may be useful to now know that the exponent is 2 so I may try to work with that as well. ;)

**Comment by Andreya-Autumn** [comment]
The linear knob travel on its own wouldn't be so bad I bet. 

It's more that the GrossBeat style delay buffer shuffling really benefits from a different control scheme than the Surge Delay has. A Playback Position control being the most obvious absentee (which those Flag modules have btw, hence the recommendation). So there's some UI/UX design to be done there which I think we'd like to do properly if we're gonna do it.

**Comment by baconpaul** [comment]
Let me tag this to #632 which is definitely related
