### ISSUE TITLE
Patch Player was deprecated/hidden without a replacement

### ISSUE THREAD

**Issue by flarn2006** [surge-synthesizer/surge-rack#996]
I see that all the modules from the old Surge plugin were deprecated and hidden in favor of the newer Surge XT. However, the Patch Player was among those deprecated, despite not having a replacement in Surge XT. Hiding a module without a replacement equates to a loss of functionality; thus, it is my opinion that Patch Player should be unhidden until/unless a direct replacement is created that preserves all functionality.

**Workaround:** Open the `SurgeRack` plugin's `plugin.json` in a text editor and look for the `"hidden" : true` under `SurgePatchPlayer`. Change it to `false`.

**Comment by Andreya-Autumn** [comment]
Hello and welcome! 

Sorry to dissapoint, but we won't do this. The reasons are, in short: 
Some of the new features in Surge XT don't build in the Rack toolchain. Some other stuff is possible but hard. 
The UI/UX etc would take a lot of thought/work to do well, which the team would currently rather put into our other projects. 
There's a good (albeit not free) way to do this already: Load Surge XT in VCV Host.

The point about deprecating previous modules without replacing them is somewhat fair. We still wanted to hide the old one though, as keeping both versions around would invite plenty confusion. The original modules were not in our perception particularly popular, but the new ones are, so we figured this was the best way forward. I think the best I can offer you here is the workaround you've mentioned, or indeed Surge XT in Host (probably a better experience). 

Issue #681 has some of the previous discussion on the matter, for reference. 

Thanks for the interest, hope you enjoy the modules otherwise!
